# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Flipez' Blog"
tagline:          "Linux & IT-Fan, Nerd, Supertüp"
url:              https://flipez.de
paginate:         1
baseurl:          /
author:
  name:           Robert Müller
  url:            https://flipez.de
  email:          github@flipez.net

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/Flipez/flipez.github.io

markdown: redcarpet
highlighter: true
hightlighter_options: ['lineanchors', 'linenos=table']
